### ISSUE TITLE
LICENSE ISSUE: Please include attribution

### ISSUE THREAD

**Issue by SomeAspy** [Lixetron/shelter-plugins#1]
Hello,
Major parts of your code are directly copied from https://github.com/Legcord/Legcord/blob/dev/src/shelter/screenshareQualityFix/index.js

This is done without attribution, (as the OSLv3 license requires) I kindly ask that you include attribution in the form of a header in the file.

You can view the terms of the license the code is licensed under here: https://opensource.org/license/osl-3-0-php

Violating files:
Majority of https://github.com/Lixetron/shelter-plugins/blob/main/plugins/screenshareQualityFix/index.jsx
Portions of https://github.com/Lixetron/shelter-plugins/blob/main/plugins/screenshareQualityFix/settings.jsx

![image](https://github.com/user-attachments/assets/f338d83e-5f79-4dd1-a517-bf4550836180)

**Comment by Lixetron** [comment]
Hello,

Thank you for pointing out the licensing issue. I have reviewed the project and added proper attribution to the relevant files. I also included the OSL-3.0 license in the LICENSE file.

**Comment by SomeAspy** [comment]
thanks!
